version: '3.8'

services:
  api:
    container_name: cassandra-explore-api
    ports:
      - 8082:8080
    image: cassandra-explore-api:bin
    volumes:
      - /var/log/container:/var/log/
    env_file:
      - files/env/.env
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
    depends_on:
      cassandra-seed:
        condition: service_healthy  # ðŸ‘ˆ wait for Cassandra to be ready
    networks:
      - cassandra-explore-network

  cassandra-seed:
    image: cassandra:4.1
    container_name: cassandra-seed
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_SEEDS: "cassandra-seed"
      CASSANDRA_NUM_TOKENS: 256
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
      CASSANDRA_START_RPC: "true"
    ports:
      - "9042:9042"
    volumes:
      - seed_data:/var/lib/cassandra
    networks:
      - cassandra-explore-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh localhost 9042 -e 'DESCRIBE KEYSPACES'"]
      interval: 20s
      timeout: 15s
      retries: 10
      start_period: 60s  # ðŸ‘ˆ Give Cassandra time to boot

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_SEEDS: "cassandra-seed"
      CASSANDRA_NUM_TOKENS: 256
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    depends_on:
      - cassandra-seed
    volumes:
      - node2_data:/var/lib/cassandra
    networks:
      - cassandra-explore-network

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_SEEDS: "cassandra-seed"
      CASSANDRA_NUM_TOKENS: 256
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    depends_on:
      - cassandra-seed
    volumes:
      - node3_data:/var/lib/cassandra
    networks:
      - cassandra-explore-network

volumes:
  seed_data:
  node2_data:
  node3_data:

networks:
  cassandra-explore-network:
    driver: bridge
